version: '3'
services:
  iam_ideflix:
    image: stephaneeveille/ideflix_iam:latest
    #  configurations nécessaires pour l'API IAM
    ports:
      - "8080:8080"
    volumes:
      - /c/temp/conf_iam:/conf_iam

  app_ideflix:
    image: stephaneeveille/ideflix_app:latest
    # configurations nécessaires pour l'application back-end
    depends_on:
      - iam_ideflix
    ports:
      - "8081:8081"
    volumes:
      - /c/temp/conf_app:/conf_app

  frontend_ideflix:
    image: stephaneeveille/ideflix_ihm:latest
    # s configurations nécessaires pour le front-end
    depends_on:
      - app_ideflix
    ports:
      - "4200:80"
